### PR TITLE
Lazy namespace

### LINKED ISSUE #18: Fully lazy version of pmap
This is a really neat library which does almost exactly what I need!

One thing kinda confused me / gave me reservations though, and that's this "eager streaming" thing. I may have gotten the wrong end of the stick about this, but I'm not really clear on why (other than  convenience for a subset of use cases) this is mandatory, rather than taking the more idiomatic clojure approach of making it lazy by default and letting people stick a `dorun` / `doseq` / `doall` at the end if they want to force the work to happen. (Incidentally I notice your examples in the README do this, which would seem to make the eagerness stuff redundant).

As you mention, eagerly consuming the input means that a lot of memory can be consumed by unrealised futures if pmapping over something like (range 1000000).

It looks like you're not holding onto the head of the input within pmap itself, nor evaluating all of the input  before work starts (which was my intitial concern).

But it seems the problem extends to any case where the consumer can't keep up with rate at which pmap generates output. In these cases you could end up bringing more and more results into memory until you get an OOM, since the consumer holds onto the head up to the point they've managed to consume up to, and the producer (pmap) is eagerly producing results faster than the consumer is advancing.

In my case I'm doing something like `(->> list-of-urls (pmap download) ... (pmap do-something-expensive))`. I can download URLs faster than I can process them. But I sure as hell don't want to eagerly bring them into memory as fast as I can download them, since I'll OOM. I don't want to buffer any more data than is required by the rate-limiting step in the pipeline, i.e. one piece of input for every thread in the thread pool which is doing the bottleneck work.

It seems to me that forcing eagerness at every step along the pipeline makes this hard to do, although it's quite likely I'm missing something. I can't see how to do this (allow the bottleneck step to rate-limit how much data is pulled through preceding steps) without laziness.

Do you have any pointers on what to do in cases like this? Or is there any chance we could add lazy pmap as an option (better yet make it lazy by default)?

Cheers!

### PR DESCRIPTION
**Pull request by leon-barrett**
This adds a whole suite of lazy parallel functions under com.climate.claypoole.lazy. This fixes #18.

### CODE REVIEW

**Comment by leon-barrett** [comment]
@mjwillson can you review this? Thanks!

**Comment by mjwillson** [comment]
Wow thanks for all the work there! This looks great to me. It seems you found a tidier way to implement it which fits better with your existing code, so that's good.

When you discuss the trade-offs of the lazy vs non-lazy in the docs, it might be worth mentioning that the lazy implementation is useful in cases where the consumer of the pmap results can't keep up with the rate at which they're produced, since it limits how big the result buffer can get in this case.

**Comment by leon-barrett** [comment]
Thanks for the doc suggestion; I've made a change in that direction.

File: src/clj/com/climate/claypoole/lazy.clj [hunk 1]
```diff
@@ -0,0 +1,249 @@
...
+
+(defn- forceahead
+  "A sequence of s with the next buffer-size elements of it forced."
+  [buffer-size s]
+  (map (fn [x _] x)
+       s
+       (concat (drop buffer-size s) (repeat nil))))
+
+(defn- pool-closer
+  "Given a sequence, concat onto its end a lazy sequence that will shutdown a
```
Comment (paraseba) [inline src/clj/com/climate/claypoole/lazy.clj]: i don't think the docstring is accurate. Or I don't understand it. This is just calling shutdown after the last element right? Maybe a nicer interface is to get a no-arg function defaulted to identity if nil. That way you have only 2 args and it's more reusable (doesn't depend on shutdown), not that you are going to reuse it, but it would be easier to understand.

Comment (leon-barrett) [inline src/clj/com/climate/claypoole/lazy.clj]: Oh, you're right, I changed the function without changing the docstring. And, I think I've made the change you desire.
